Job launching after 0.65 seconds in submission.
Running python job.
Changed into dir /Users/naveenmirapuri/PycharmProjects/SpearmintImplementation/Spearmint-master/Vineet_Optimization
Importing Vineets.py
Using TensorFlow backend.
Running Vineets.main()
Anything printed here will end up in the output directory for job #504
{u'num_conv_filters_2': array([46]), u'num_units': array([490]), u'num_conv_filters_1': array([15])}
Traceback (most recent call last):
  File "/Users/naveenmirapuri/PycharmProjects/SpearmintImplementation/Spearmint-master/spearmint/launcher.py", line 245, in launch
    result = python_launcher(job)
  File "/Users/naveenmirapuri/PycharmProjects/SpearmintImplementation/Spearmint-master/spearmint/launcher.py", line 329, in python_launcher
    result = module.main(job['id'], params)
  File "/Users/naveenmirapuri/PycharmProjects/SpearmintImplementation/Spearmint-master/Vineet_Optimization/Vineets.py", line 134, in main
    return model(params['num_conv_filters_1'], params['num_conv_filters_2'], params['num_units'])
  File "/Users/naveenmirapuri/PycharmProjects/SpearmintImplementation/Spearmint-master/Vineet_Optimization/Vineets.py", line 36, in model
    model.add(Conv2D(num_conv_filters_1, (3, 3)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/sequential.py", line 185, in add
    output_tensor = layer(self.outputs[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/base_layer.py", line 440, in __call__
    self.assert_input_compatibility(inputs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/base_layer.py", line 345, in assert_input_compatibility
    x_shape[int(axis)] not in {value, None}):
TypeError: unhashable type: 'numpy.ndarray'
Problem executing the function
(<type 'exceptions.TypeError'>, TypeError("unhashable type: 'numpy.ndarray'",), <traceback object at 0x10b9a3bd8>)
Job failed in 3.67 seconds.
